--[[
A copy of getfenv(0).
For whatever reason, getfenv(0) refuses to return all of the global elements,
so this had to be done manually. The drawback is that now updates aren't received
automatically. I'll try to update this frequently if it becomes popular.
Anyway, all the major/necessary methods *should* be in here.
--]]

return {
	Axes = Axes,
	assert = assert,
	bit32 = bit32,
	BrickColor = BrickColor,
	CFrame = CFrame,
	Color3 = Color3,
	coroutine = coroutine,
	ColorSequence = ColorSequence,
	CatalogSearchParams = CatalogSearchParams,
	debug = debug,
	delay = delay,
	DateTime = DateTime,
	DockWidgetPluginGuiInfo = DockWidgetPluginGuiInfo,
	Enum = Enum,
	error = error,
	File = File,
	Faces = Faces,
	FloatCurveKey = FloatCurveKey,
	getfenv = getfenv,
	getmetatable = getmetatable,
	game = game,
	gcinfo = gcinfo,
	Instance = Instance,
	ipairs = ipairs,
	loadstring = loadstring,
	math = math,
	newproxy = newproxy,
	next = next,
	NumberRange = NumberRange,
	NumberSequence = NumberSequence,
	NumberSequenceKeypoint = NumberSequenceKeypoint,
	os = {
		time = os.time,
		date = os.date,
		clock = os.clock,
		difftime = os.difftime,
	},
	OverlapParams = OverlapParams,
	print = print,
	pairs = pairs,
	pcall = pcall,
	plugin = plugin,
	PathWaypoint = PathWaypoint,
	PhysicalProperties = PhysicalProperties,
	Ray = Ray,
	Rect = Rect,
	Random = Random,
	rawget = rawget,
	rawset = rawset,
	Region3 = Region3,
	require = require,
	rawequal = rawequal,
	Region3int16 = Region3int16,
	RaycastParams = RaycastParams,
	RotationCurveKey = RotationCurveKey,
	setfenv = setfenv,
	spawn = spawn,
	script = script,
	select = select,
	shared = shared,
	string = string,
	settings = settings,
	setmetatable = setmetatable,
	time = time,
	tostring = tostring,
	task = task,
	tick = tick,
	type = type, -- Not sure why this is highlighted as a keyword.
	table = table,
	typeof = typeof, -- This shouldn't be highlighted as a keyword, either...
	tonumber = tonumber,
	TweenInfo = TweenInfo,
	TextChatMessageProperties = TextChatMessageProperties,
	UDim = UDim,
	utf8 = utf8,
	UDim2 = UDim2,
	unpack = unpack,
	UserSettings = UserSettings,
	Vector2 = Vector2,
	Vector3 = Vector3,
	Vector2int16 = Vector2int16,
	Vector3int16 = Vector3int16,
	wait = wait,
	warn = warn,
	workspace = workspace,
	xpcall = xpcall,

	--/Deprecated methods
	collectgarbage = collectgarbage,
	Delay = Delay,
	ElapsedTime = ElapsedTime,
	elapsedTime = elapsedTime,
	Game = Game,
	printidentity = printidentity,
	Spawn = Spawn,
	Stats = Stats,
	stats = stats,
	Version = Version,
	version = version,
	Wait = Wait,
	Workspace = Workspace,
	ypcall = ypcall,
}
